# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Glad_config = debug
  GLFW_config = debug
  ImGui_config = debug
  SPIRVCross_config = debug
  Snow_config = debug
  Glacier_config = debug
endif
ifeq ($(config),release)
  Glad_config = release
  GLFW_config = release
  ImGui_config = release
  SPIRVCross_config = release
  Snow_config = release
  Glacier_config = release
endif
ifeq ($(config),dist)
  Glad_config = dist
  GLFW_config = dist
  ImGui_config = dist
  SPIRVCross_config = dist
  Snow_config = dist
  Glacier_config = dist
endif

PROJECTS := Glad GLFW ImGui SPIRVCross Snow Glacier

.PHONY: all clean help $(PROJECTS) Vendor

all: $(PROJECTS)

Vendor: GLFW Glad ImGui SPIRVCross

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Snow/vendor/Glad -f Makefile config=$(Glad_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Snow/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Snow/vendor/imgui -f Makefile config=$(ImGui_config)
endif

SPIRVCross:
ifneq (,$(SPIRVCross_config))
	@echo "==== Building SPIRVCross ($(SPIRVCross_config)) ===="
	@${MAKE} --no-print-directory -C Snow/vendor/SPIRV-Cross -f Makefile config=$(SPIRVCross_config)
endif

Snow: Glad ImGui GLFW SPIRVCross
ifneq (,$(Snow_config))
	@echo "==== Building Snow ($(Snow_config)) ===="
	@${MAKE} --no-print-directory -C Snow -f Makefile config=$(Snow_config)
endif

Glacier: Snow Glad ImGui GLFW SPIRVCross
ifneq (,$(Glacier_config))
	@echo "==== Building Glacier ($(Glacier_config)) ===="
	@${MAKE} --no-print-directory -C Glacier -f Makefile config=$(Glacier_config)
endif

clean:
	@${MAKE} --no-print-directory -C Snow/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Snow/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Snow/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Snow/vendor/SPIRV-Cross -f Makefile clean
	@${MAKE} --no-print-directory -C Snow -f Makefile clean
	@${MAKE} --no-print-directory -C Glacier -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   SPIRVCross"
	@echo "   Snow"
	@echo "   Glacier"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"