# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Snow_config = debug
  Glacier_config = debug
endif
ifeq ($(config),release)
  Snow_config = release
  Glacier_config = release
endif
ifeq ($(config),dist)
  Snow_config = dist
  Glacier_config = dist
endif

PROJECTS := Snow Glacier

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Snow:
ifneq (,$(Snow_config))
	@echo "==== Building Snow ($(Snow_config)) ===="
	@${MAKE} --no-print-directory -C Snow -f Makefile config=$(Snow_config)
endif

Glacier: Snow
ifneq (,$(Glacier_config))
	@echo "==== Building Glacier ($(Glacier_config)) ===="
	@${MAKE} --no-print-directory -C Glacier -f Makefile config=$(Glacier_config)
endif

clean:
	@${MAKE} --no-print-directory -C Snow -f Makefile clean
	@${MAKE} --no-print-directory -C Glacier -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Snow"
	@echo "   Glacier"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"