#pragma once

#define SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, CONST, A, B)\
	Vector<2, T> A ## B() CONST {\
		return Vector<2, T>(this->A, this->B);\
	}

#define SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, CONST, A, B, C)\
	Vector<3, T> A ## B ## C() CONST {\
		return Vector<3, T>(this->A, this->B, this->C);\
	}

#define SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, CONST, A, B, C, D)\
	Vector<4, T> A ## B ## C ## D() CONST {\
		return Vector<4, T>(this->A, this->B, this->C, this->D);\
	}

#define SNOW_SWIZZLE_GEN_VECTOR2_ENTRY_DEF(T, L, CONST, A, B)\
	template<typename T, Q>\
	Vector<L, T> Vector<L, T, P>::A ## B() CONST {\
		return Vector<2, T>(this->A, this->B);\
	}

#define SNOW_SWIZZLE_GEN_VECTOR3_ENTRY_DEF(T, L, CONST, A, B, C)\
	template<typename T, Q>\
	Vector<L, T> Vector<L, T, P>::A ## B ## C() CONST {\
		return Vector<3, T>(this->A, this->B, this->C);\
	}

#define SNOW_SWIZZLE_GEN_VECTOR4_ENTRY_DEF(T, L, CONST, A, B, C, D)\
	template<typename T>\
	Vector<L, T> Vector<L, T>::A ## B ## C ## D() CONST {\
		return Vector<4, T>(this->A, this->B, this->C, this->D);\
	}


#define SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR2_SWIZZLE(T, P, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, 2, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, 2, const, B, A)

#define SNOW_SWIZZLE_GEN_REF_FROM_VECTOR2(T)\
		SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR2_SWIZZLE(T, x, y)\
		SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR2_SWIZZLE(T, r, g)\
		SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR2_SWIZZLE(T, s, t)

#define SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, B)

#define SNOW_SWIZZLE_GEN_REF3_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, A)

#define SNOW_SWIZZLE_GEN_REF_FROM_VECTOR3_COMP(T, A, B, C)\
		SNOW_SWIZZLE_GEN_REF3_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR3_SWIZZLE(T, A, B, C)

#define SNOW_SWIZZLE_GEN_REF_FROM_VECTOR3(T)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR3_COMP(T, x, y, z)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR3_COMP(T, r, g, b)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR3_COMP(T, s, t, p)

#define SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, C)

#define SNOW_SWIZZLE_GEN_REF3_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, B)

#define SNOW_SWIZZLE_GEN_REF4_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, B, A)

#define SNOW_SWIZZLE_GEN_REF_FROM_VECTOR4_COMP(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_REF2_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_REF3_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_REF4_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)

#define SNOW_SWIZZLE_GEN_REF_FROM_VECTOR4(T)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR4_COMP(T, x, y, z, w)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR4_COMP(T, r, g, b, a)\
		SNOW_SWIZZLE_GEN_REF_FROM_VECTOR4_COMP(T, s, t, p, q)

#define SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR2_SWIZZLE(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, B)

#define SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR2_SWIZZLE(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, B)

#define SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR2_SWIZZLE(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, B)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR2_COMP(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR2_SWIZZLE(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR2_SWIZZLE(T, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR2_SWIZZLE(T, A, B)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR2(T)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR2_COMP(T, x, y)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR2_COMP(T, r, g)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR2_COMP(T, s, t)

#define SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, C)

#define SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, C)

#define SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, C)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR3_COMP(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR3_SWIZZLE(T, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR3_SWIZZLE(T, A, B, C)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR3(T)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR3_COMP(T, x, y, z)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR3_COMP(T, r, g, b)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR3_COMP(T, s, t, p)

#define SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR2_ENTRY(T, const, D, D)

#define SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, A, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, B, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, C, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR3_ENTRY(T, const, D, D, D)

#define SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, A, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, B, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, C, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, A, D, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, A, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, B, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, C, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, B, D, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, A, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, B, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, C, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, C, D, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, A, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, B, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, C, D, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, A, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, A, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, A, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, A, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, B, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, B, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, B, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, B, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, C, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, C, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, C, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, D, A)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, D, B)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, D, C)\
		SNOW_SWIZZLE_GEN_VECTOR4_ENTRY(T, const, D, D, D, D)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR4_COMP(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR2_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR3_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)\
		SNOW_SWIZZLE_GEN_VECTOR4_FROM_VECTOR4_SWIZZLE(T, A, B, C, D)

#define SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR4(T)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR4_COMP(T, x, y, z, w)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR4_COMP(T, r, g, b, a)\
		SNOW_SWIZZLE_GEN_VECTOR_FROM_VECTOR4_COMP(T, s, t, p, q)
